import { SiteSettings } from "@/src/types";

export const DEFAULT_SETTINGS: SiteSettings = {
  siteName: {
    value: "Penstack",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
  },
  siteDescription: {
    value:
      "Penstack is a modern, clean, and minimalistic and customizable nextjs blog",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
  },
  siteOpengraph: {
    value: "",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
  },
  siteLogo: { value: "", enabled: true, encrypted: false, canEncrypt: false },
  siteLogoMobile: {
    value: "",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
  },
  siteFavicon: {
    value: "",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
  },
  maintenanceMode: {
    value: "false",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
  },
  gaId: { value: "", enabled: false, encrypted: false, canEncrypt: false },
  gtmId: { value: "", enabled: false, encrypted: false, canEncrypt: false },
  mixpanelToken: {
    value: "",
    enabled: false,
    encrypted: false,
    canEncrypt: true,
  },
  posthogKey: { value: "", enabled: false, encrypted: false, canEncrypt: true },
  posthogHost: {
    value: "https://app.posthog.com",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
  },
  sentryDsn: { value: "", enabled: false, encrypted: false, canEncrypt: false },
  sentryEnvironment: {
    value: "production",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
  },
  errorTracking: {
    value: "false",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
  },
  performanceMonitoring: {
    value: "false",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
  },
  resendApiKey: {
    value: "",
    enabled: false,
    encrypted: false,
    canEncrypt: true,
  },
  cloudinaryName: {
    value: "",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
  },
  cloudinaryApiKey: {
    value: "",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
  },
  cloudinaryApiSecret: {
    value: "",
    enabled: true,
    encrypted: false,
    canEncrypt: true,
  },
  maxUploadSize: {
    value: "10",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
  },
  defaultMediaFolder: {
    value: "uploads",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
  },
  apiRateLimit: {
    value: "100",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
  },
  cacheDuration: {
    value: "30",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
  },
  emailFrom: { value: "", enabled: true, encrypted: false, canEncrypt: false },
  newsletterEmailFrom: {
    value: "",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
  },
  emailFromName: {
    value: "",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
  },
  localPostAnalytics: {
    value: "",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
  },
  showSiteNameWithLogo: {
    value: "",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
  },
};
